# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false   # true for Unit Test reporting
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    #Include the following for Code Coverage
    #    codeCoverageTool: 'JaCoCo'
    #summaryFilelocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    #reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
